files:
  - source: /docs/**/*.md
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_path%.%file_extension%
project_id_env": "CROWDIN_PROJECT_ID" # Low priority
api_token_env": "CROWDIN_PERSONAL_TOKEN" # Low priority
